### ISSUE TITLE
Bulk purge old revisions

### ISSUE THREAD

**Issue by odie2** [ethitter/WP-Revisions-Control#3]
Hi,

I have even more than 10 revisions to one post because I migrated from old Joomla to WordPress with ~450 posts, so it's incredible amount of revisions.

I limited revisions for posts to 4 and for pages 5.

But I would remove those that "overflows" limits. As I saw there are only option to purge all revisions and only for single post/page.

I could do it by SQL in my database, but it would be nice to have option to do it bulk from WordPress. Exactly the same way like [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) do - you could go to **Tools** and regenerate every thumbnail or go to **Media Library**, choose some images by checkboxs and choose regenerate action from bulk action's dropdown.

Or maybe there are already something like this, but I couldn't find it?

Greetings

**Comment by ethitter** [comment]
Thanks for the suggestion! I've made a note of this idea at https://git.ethitter.com/wp-plugins/wp-revisions-control/issues/1.

**Comment by ethitter** [comment]
When released, version 1.3 will include two bulk actions: one to purge selected objects' excess revisions, the other to purge all revisions for those objects.

**Comment by sootedninjas** [comment]
How do you do the bulk delete? is it just for a single post or for entire site?
