### ISSUE TITLE
Make Gutenberg show blank page

### ISSUE THREAD

**Issue by vslonska** [ethitter/WP-Revisions-Control#6]
Hello,

Thanks for the plugin, but now if activated if prevent Gutenberg from working (blank page).

If you desactivate the plugin, Gutenberg works.

Thanks for your help,

**Comment by ethitter** [comment]
Thanks for the report. This was likely an issue with pre-release versions of Gutenberg, as I've successfully tested this plugin against each WordPress release that's included the block editor.
